### ISSUE TITLE
Relays do not switch when powered via VSYS

### ISSUE THREAD

**Issue by lewiswalsh** [sbcshop/Raspberry-Pi-Pico-Relay-Board#1]
Powering the board via the USB port works as expected. But when powering through VSYS and GND the relays do not switch. Is it possible to power any other way than the USB port?

**Comment by sbcshop3** [comment]
Relay needs stable 5V for operation and so relay 5V drive supply is connected with VBUS. Therefore, if no supply at VBUS means no trigger voltage for relay. Refer schematic for more detail: https://github.com/sbcshop/Raspberry-Pi-Pico-Relay-Board/blob/main/Design%20Data/SCH_PICO%20RELAY%20BOARD.pdf
